export default defineEventHandler(async (event) => {
    // TEST ENDPOINT: Create a dummy long transcript for UI testing
    const config = useRuntimeConfig()
    const body = await readBody(event)

    const { week } = body

    if (!week) {
        throw createError({
            statusCode: 400,
            message: 'week is required'
        })
    }


    const { data: profileData, error: profileError } = await supabaseClient
        .from('profile')
        .select('user_id')
        .eq('role', 'prof')
        .limit(1)
        .single()

    if (profileError || !profileData) {
        throw createError({
            statusCode: 400,
            message: 'No prof user found in database'
        })
    }

    const userId = profileData.user_id

    try {


        const longTranscript = `So these are the learning. Now we are in the problem space, still in the problem space. We finished modelling and now we are going to do the analysis. We finished modelling, we are finding the analysis. In this stage the output will be issues and recommendations. So you can see that the as-is models and the business needs will help us to do process analysis. In outputs from the previous two stages, take your workflow diagram, analyze, take the interview script, analyze, this is the stage that we have. So you have previous outputs as inputs to this particular stage. So how a methodological approach is given for this analysis? So analyzing any particular business process requires both dynamic and static approaches, manual as well as tool-based approaches. Sometimes you cannot understand or analyze with a tool. You have to be in person watching this entire business process and then collect the information or issues. Therefore, manual analysis. Why do you think we are having surveys? When students complain about certain problems in SMU, we do surveys, we do focus interviews. We could have just based on the tool and say okay just use the tool and then we don know Tool can get only certain information So manual analysis is very important stage So, we have manual analysis, which we get it as a root cause analysis, and of course, static reports, when you use a proof. So, this will be static analysis stage. And this is the dynamic analysis stage. So, simulation is very popular. Without simulation, you cannot analyze the numbers. So we need numbers also, right? So how do we get the additional numbers in a dynamic way? That's where you can actually come. Static analysis gives you certain types of numbers. But dynamic analysis will give you a real setting, almost close to the real setting kind of numbers. So both of them have a very important purpose. This analyzes, for example, static analysis in software engineering or in business process management.

Let's see the differences. In software engineering, you do a quick analysis when you write a program. You go and check for the logic. You go and check for whether your if-else groups are in proper way or so. That is known as analyzing the program code without even executing the program. So the second kind of analysis which is dynamic is you have test cases. run those test cases and then check which is simulating your approach. Same thing happens here in business management. We have to take interview scripts as is diagrams and use the static analysis Okay So this is a very important stage because the first step we will be able to get static report and RCI report We will see these two reports today. And the second step we will come up with the RCI report. Okay, all of them are tables. So far we have been drawing different rotation BPMN notation. Here we are getting papers. So we'll start with static reports. So the static reports is helping, is trying to use the tool and get the as-is report in a static manual. Since you don't run the simulations, you simply put all the data inside and then just ask for the static report. So there are different ways the tools function. If you use IPM workflow process, it's a very powerful tool. It gives more than seven to eight static reports. Whereas SignalView hardly gives two to three reports. So it really depends on different types of tools that you are using. So at this stage, it's just to understand the cost, time, and so of course, of course, to get the issues and so on related to the particular numbers. So if you see, oh, okay, the cost is really high. Which activity is having more cost? You can see more clearly at the activity level Okay so these are certain things that your static reports provide Cost calculation and resource calculation Resources here, human resources or machine resources. Both of them you will be able to analyze. As I mentioned, it has to vary the different tools.

The different tools you can just see and adapt accordingly. This is an example that our SIGNAVIA tool is going to provide. So here as you notice, this is known as cost calculation process. Okay? Let me show you. Cost calculation process and it mentions what is the name of the process. This is very important, frequency per year. So we are calculating for the entire year. How do we get 6500? 6500 is the instances. So how many rental applications we are getting per year. Which means we will know how many we are getting per month, per week, and per day. We average out and then try to use the numbers. Okay? And then you can notice that every task is provided here. Okay? This input factor is very interesting. The input factor comes from the decision boxes. So if you have a decision box followed by another decision box, then obviously there is a split. So 100 instances goes in  path is 75% and this path will be 25%, then this is only 75% moving. And then again if you split this, let's say this is 50% or 75% and again 25%, what should be this? 75% of So, it will not, it will get reduced. That's what is your input factor drawing. So, the activity over here can happen only fewer times, not all 100 customers will reach to this activity. Only 75% of 75 customers will reach this activity. So this is the indication to say that this activity happens only 75% of the patients. We can actually create this report even using Excel spreadsheet. And then you have cost for institution. Where are these costs coming from? For each activity do you say what is the cost? Will you be able to capture the cost during the interviews? No? Think again. At activity you will be asking only the time part. You don't know the cost. So how are we calculating the cost The rate of hours Correct man hours Okay so man hours and the amount you pay per hour So we say that this MO is paid let say per hour and if he is using 5 minutes or 10 minutes for this then we will be calculating the cost for that activity.

And if you multiply it for 6500 times, times 75 percent because it happens only 75 percent of the time, you get your total cost. So this is your cost to run the activity and this is the total cost. Now sometimes we will also have some external costs. Let's say when MO is checking the UEN number, every time you check the UEN number, the government charges you. 10 cents, 50 cents, something like that. Or every time the courier collects the courier from your office, they will charge you. That becomes an activity charge. So that is an external activity charge that can be added to your process. You can see there can be multiple scenarios. Don't worry, we will see different types of scenarios in our examples. So this is a resource calculation. Now you will notice that we'll have each resource on the top and the corresponding task One more resource and more and the task Okay You can notice that CSO is performing CSO gathers the task So this task is done by the, completed by the CSO. And office dispatcher means I have someone part of the report, it is office dispatcher. Again, and more. Okay? So now, time taken for execution. Workload for running 6500 because we started with 6500. And then workload for 8.0. Personal allowance time. So why am I giving you all this quick description? Later in lab 4 you will be seeing all these numbers. And don't get panicked, they are very straightforward numbers. You are just using the numbers of manpower as well as the cost, time for the app. That's all. So these are the triggers, number of triggers coming from your starting, start trigger. So what is this including personal allowance time? This personal allowance time is trying to say that even though you expect MO to have 100% of his time to be dedicated to the workplace, It is impossible for everyone to work that number of 5 times 7 days, 8 hours a week, 5 days a week.

So this is not really possible What will happen A person may be taking a vacation time may be having a sick time and so on So already somebody did some research, they said that on average a person will be taking more than 10% of the personal time from the actual workload. So you'll be getting only 90% of what you're seeing. So that's already very good at it. It's already very good. Okay? So, Signavia allows you to add this personal time. Okay? So, that completes a very brief introduction of today's lab. So, today's lab, you are going to complete the static analysis report, and you'll be generating those reports. Okay? There are four videos, very straightforward videos for you to use, use and then start running your static analysis report on the same rental application. Okay, now manual analysis. We learn a lot during the manual analysis. So any process given, I have to start a manual analysis. I'll be building a RCI table. Okay, so we call it as RCI model still, but it is, it looks more like a table. Okay, it's a diagram, a model. So root cause impact model is not new. You have been seeing it even in your JEC, even in your secondary. Everybody will ask you what is root cause. You see a problem, they'll ask you for a root cause  So the root cause model helps you identify the issues. And it will help you to identify the cause for the issue as well. Finally, multiple issues can actually be pointed to one root cause. You can ask the question, why are you late to the school? I didn't wake up. Why you didn't wake up? Because you are alarming. Why are you late to the school? Because I missed the bus. Why you missed the bus? Because I woke up late. Why you woke up late? I missed it. I didn't, the alarm didn't. Why your alarm didn't ring? I didn't set it. So you see different ways answered you go, you still go back to the alarm mode. The root cause is you didn't set your alarm. So there are different ways that you are going to answer the path.

Let's look at this interesting, I love this video, okay? So this particular video helps us to understand about root cause analysis. Okay this is our famous Titanic example Let me increase the volume Do I have to reduce the switch of the lights or is it okay? So pay attention, we are learning about a 5Y approach. approach. Means we are asking why, why are you late because this happened, why this happened, because this happened and so on. So he's explaining the 5y approach. There is even 6y, 7y, 8y and so on. For this course we will be restricting to 5y and usually when you come to the third y you already know the root cause. Okay, he'll show you different ways of coming to the root cause and this problem is in the context of dynamic shape. Okay, so let's get started. I'll be pausing here and there to get your inputs and we learn watching this video by now. This is a simple example of how to conduct a 5Y. What I'm showing is a 1Y. It points out that the Titanic sank because the ship hit an iceberg. It's a simple cause and effect relationship. You can expand on this and say the Titanic sank specifically because water filled the hole and water filled the hole because there are openings in the hole and there are openings in the hole because the ship hit the iceberg These are three one Y that combine create a 3Y This information in the middle of this part of the analysis fits right in here So the 1Y is accurate and the 3Y is accurate You can add more detail and expand this to a 5Y On this 5Y it points out that the ship hit the iceberg because it didn turn sufficiently because the lookout saw the iceberg light and you can see how easy it is for someone to identify that the lookouts are what caused the Titanic to sink. This 5Y is absolutely accurate. The lookouts, seeing the iceberg late, is causally related to the Titanic sinking. But someone else on the same issue could say, no, the problem is the ship didn't turn sufficiently because it was going too fast.

Management had the ship going at 18 knots. It's too fast. It couldn't turn sufficiently. So it's really a management systems issue. And someone else says, no, what happened is the plates pulled apart because of the strength of the joints, because of the rivets. These were great for wrought iron rivets. And if you would have just changed the design of those rivets, you never would have a Titanic sink because the plates wouldn't have pulled apart. So what we notice here, for the same issue, we can actually find three different reasons or causes Okay Do you have to solve each of these causes This one this one and this one There are three different five whys laid out here Each one of these five. Do you have to solve everyone, every operations problem, management problem, as well as the design problem, or just solving one problem is sufficient? One cost, one root cost. You solve one root cost, already your Titanic, So, remember this particular approach helps us to come up with different causes. Which one is the most reasonable cause and the cause that can be handled more easily will be the approach we will take it during the recommendation stage and also for the due cause analysis stage. I can take all of them, probably design is the one which cannot be solved at all so it is much more critical so we should not go for the design approach. And maybe operations is much more easier approach so we go with the approach and then we'll just choose operations as the, this path, only one path. This path for all good customers. Don't list all three as your causes. It doesn't work. The same issue, you don't want to put all three different reasons for that issue, okay. So it continues with the 6y and 7y and so on, which we are not interested. I just want to let you know that there can be multiple ways that you can look into the problem and the causes of the problem  What we are interested is in only one row. Just choose the one row.

Each row you will usually choose is the row which is more easier to implement or the row which will be more impactful and so on. Okay? So we'll see those with the examples. But let me now put this into a root cause impact diagram. So the root cause impact diagram looks something like this. So you have issue number. You have to list on all the issues in the business process. There are only one issue and then multiple issues. Only then you want to do an improvement for your business process. It's just one issue, just ignore it. Multiple issues. Then you have to explain what is the problem. Titanic sign. It's a problem. Explain that particular problem. And your issues should really sound like an issue. I'll show you an example where it feels. Then comes the cause. So why did this issue happen? and the cause should answer why this issue came. So that's your first why. After the first why, you continue to ask more why's until you come to one root cause. How to choose the root cause? We will show you examples, but the idea is you have to come to one root cause. So by now you can understand there are many issues. Some of them will be under the same root cause. So if you have 50 issues, you will be having only 7 to 8 root causes 50 issues but only 7 to 8 root causes Does this make sense Keep asking you be going back to some similar root cause This root cause falls under a category. So he explained just now that each of them have a category. This is the root cause he got into. And then he said that this is operations category. This is management category. So he'll try to categorise those group courses. Okay? So that's the group course type. These two are the important numbers for business users. See, it's very important as an IT graduate not to just think about the solution. You will always go back to, oh, I have a problem. Oh, I can give you the tool. Nobody wants that now. People are very smart. The business users became very smart. They just don't want to see the tool.

There are hundreds of tools. So they need the numbers. Without numbers it is not going to work. So they want to understand, do you know my problem clearly before you are offering me the tool? So this is where your skill is. You need to understand what is the problem of the business user in a systematic manner. And when you do that, numbers become important. So here, the issue analysis tells you which business performance metric is affected. Is it the time factor? Is it a cost factor Is it the number of customer complaints Everything will be bad And lastly what is the impact level So if it a huge impact level then in this issue is a red flag Must, must solve. Okay? So I pause here, ask me questions before I pause you to the next one. Okay? So these two items you have to decide for yourself in your project because you don't have a real business user for your project. You can decide these two members. But they will be very direct, particularly for the business performance. when you see the issue, you know that it should be something to do with the quality, or it should be doing with some of the customer complaints, and so on. You will be able to see a number of errors, so that number is easier to find. But impact level, you have to slightly manage, depending on which issue you want to, you do a reverse engineering. Which issue you want to solve, pick up that issue and say that it is high impact, therefore I'm solving it. So honestly, So you see, for the project really, this is not relevant for us. It not But in the real business setting this is so important because your business user must learn this issue is very serious So the assignment of the numbers is quite arbitrary Yeah this part is accurate So you just have to justify why you choose this number. So it's stating that, okay, for this particular company, the customer complaints is very critical. We cannot answer that. Whereas for the warehouse process, the losing how many products are lost, etc. is important.

Therefore, we choose this as a high income. Another problem is wastage of food. So the quantity of the wastage of food is critical, therefore reduce this issue as high critical. So depending on the domain, it has to change and you have to re-engineer it. And you should understand that there are seven different projects inside this classroom. So every student will come up with different types of problem solving, hence the impact levels. For the impact level, is this something that's agreed upon between the client and the analyst, or is this something that the analyst just picks and moves on? Okay, so the client has to give you. The business user has to give you. Because this story has to be pretty clear that the business needs. Just like with students, when the students raise certain complaints, For example, bidding system, you should know that 20 years back, the bidding system was really loose. After that, we did some process improvements and so on. Now it has certain shape. I don't agree that it is really perfect, and it is not  I know it is very challenging but we have to limit this kind of process in SMU. Okay. For our project, let's say we identified this issue that is very low level and do we still have to write down? Okay, so we gave certain specifics. We asked you to list down I think six issues and then try to choose four issues to solve in the data part. So the same thing, just follow the numbers. It is any kind of issue. It might seem to be very insignificant. It doesn't matter, just least. The most important four issues which you are solving later are the critical ones which move on to the next stages of your project. Okay, so let's move on. For the issue description, it should be helping us to know what is the issue. and partially it has to tell how the business performance is effective. So make sure that these two parts are there inside the issue. So it should have what is the issue and how the performance is effective.

It actually wastes the time of the marketing officer. Or marketing officer has more rejected cases for the marketing officer, which wastes the cost based on the expenses So some numbers some business performance have to be inside this issue Next for the cause description it has to tell why the issue happened So there should be a cause effect loop here. So when I ask why issue, this is the cause. So it should be a proper why. Now root level cause. Root cause is the top level cause. Sometimes the second y itself will give you the root cause. Never mind, put the root cause. But the root cause will be a very short term which will give you some examples. Okay? So the root cause can be a very short term. It can be a direct output of the same, similar to the cause, but it has to be just simply coming from the second y itself, which is okay. Okay? So one y, second y, three y, five y. Anything is okay. This root cause is used to move on to the recommendation stage. Now what are the issue categories? This is where you find problems, okay? I'll give you examples and make it very clear for you, I'll try. I'll try to make it very clear for you to choose what is the technique. So always think about the Titanic example. In Titanic example he mentioned about operations problems. So that particular operation is where the lookouts have to be arranged. It should be arranged more number of lookouts have to be arranged All these are operations related Second he mentioned about management problem Because the management wants to go with certain speed this is a decision made by the management So that is a management policy and so on. He also mentioned about the design problem, which is some technical kind of issues and so on. So you should be able to understand what kind of issues fall into these categories. root causes will fall into these categories. So let's say there are, for us, operations is very similar to your process. So we have process related category, system related.

System related is your IT systems. We are interested in IT systems. Okay, I'm not interested in another kind of collaboration models and all those things, no I'm not interested. We are talking about a proper IT applications. Then comes the collaborations, et cetera, fall under the people related. Okay, so work attitudes, lack of skills, are there not enough training background or education background? These are all the people related. So if we see that this problem happened because of the people related, you have to throw it into the people related. Policies is where the management has created certain regulatory frameworks. or government has created such regulatory frameworks. Then you can happily put them into the policy, okay. To my experience all our projects will fall into these four categories Very rarely which you cannot place in any of these things you can put it into others but not necessarily. We'll agree once, I saw it. So, four categories are sufficient. So, process-related, non-automation is not same as system-related. When process is not automated means it is being done manually, that's all. Don't blame the system. Blame the process. Okay? So, usually non-automation scenario, the students get confused and they try to put it under the system related. Non-automation is not system related. It's your process. Your process is meant to be manual. So, today's webinar is teaching. Of course, it's process related because manual. Maybe after five years you'll be having some AI teaching in this classroom. So then you can blame this AI. It is a system related problem. Okay? So as long as manual things are happening, this non-automated, say the process is not automated. So now think what is happening inside the process. The process has activities, the sequence of activities, the arrangement of decision boxes and so on. Any problem with such arrangements, activities, call everything as processes. Only, only if there is a problem with the IP.

Example, this particular eLearn system, the feature  So then you claim the E-Learn. Or certain feature is not available, then you claim the E-Learn. Okay? So lack of system features or lack of integration. So for example, in system E-Learn, it shows your grade as A, but in your I-Sys, your grade is displayed as B. It's a big problem. So it is a system problem, system integration problem. So this course you have to start thinking like an IT person when you are talking about system related. People related is very straightforward and policy manages anything through the regulatory aspects, policies etc. go into the policy. Take a minute, ask me questions. For policy related, is really just like, the blame will be on how policies are constructed or the nature of the policy? Okay. Usually you will claim the policy to the department and to the management and so on. Any type of policy which is creating an issue inside your process. Maybe because of that policy, your activity time is increasing. So for example the SMU will say that this particular okay the faculty certain type of document should be manually signed Then that has created an unnecessary time change for the faculty right So why are you doing it You have to still do it because university has such a policy. Okay, unless otherwise university is ready to change the policy, yes. Okay, sometimes the policies can be changed because they're outdated. Last time, yes, you have to do manual signature. Now who is doing the manual signature? It's all secure. Cybersecurity is already in place. So even the digital signatures are equipped. So don't think that the policies cannot be changed. Policies have to change. I don't know any law student here. They will always say that yes, policies have to change. Now one thing that we have to be very careful is blaming the government for the number. So if you ask too many why's, then it will happen something like this. Why you didn't switch on the alarm? Oh, in the night I slept late.

Why you slept late? I was watching the movie. Okay, we were watching the movie. Why you were watching the movie? For the entertainment. Why you wanted the entertainment? God only knows. Or when I say I'm stressed. Why are you stressed? It just goes on. I mean, meaningless. Or in the end, you will say everything. Oh, I don't know. God only knows. Or you will just take the government. So don't ask too many why's which are meaningless. Okay? It has to fall into one of the categories. Once you find the category, okay, stop. You know you can solve the problem Don ask too many whys There is one nice video about these why and then they keep on asking why goes to the government leadership of the government Lastly, the business metrics, I already mentioned about these. I just want to ask you, the problem comes from external partners, how do we even understand the process and good causes of distribution of this? So whenever these external partners are involved, let's say you would say the FedEx takes much longer time or the FedEx people do not have proper communication mechanism, do you think they are going to change? can we make any changes to them we can't change them so don't put them into the other category so when there are some external parties involved and this problem is inevitable you have to still treat it as within your process how you can improve it how you can still reduce the impact of it if you can't reduce the impact of it you have to agree that fact so you will just I'll show you one example later on where the external parties or certain policies will come into the picture, and then how you can solve such kind of problems. Okay? Just… So let's say this is a government policy which requires a sign of the bill of sales on the paper. Now this is the policy that has been already in place.

Now you are a real estate agent, property guru, there is another real estate agent, I don't know, somebody A, B, C, D, all different real estate agents are facing the same problem because it takes up almost half day to two days which is unnecessary time and cost for the process. So what they can do is they have to come together and put a policy change to the government, a request of policy change to the government, right? So these kind of external parts, same thing. If you have the FedEx problem, you have to form a team or a group or union and ask for a request, change certain things from the FedEx. Whether it is going to happen or not going to happen, it's quite difficult to say. I'll show you one more example. So if suppose you are trying to come with certain kind of changes, a recommendation, and that recommendation might solve or vary,  It can be a very good solution, but it can be very complex to implement. Okay? So that's the reason why you have to combine both of them and then choose the most suitable solution. In some root cause, you mentioned that it is because of the external. But while you're solving certain root causes, some other issues can be just disappeared by themselves. Even if you put it under others, sometimes that problem could have been totally removed. Because you have created your own FedEx kind of system, or you would have created another approach to it, so this will solve the problem while you're solving other issues. So remember, don't think that you can solve the problems related to external parties. It's very, very difficult for implementing. We will also show you examples of impact models for the recommendations. Can the root cause the policy? For example, in the hardware model, there's a group called the system. So choose one of them. The policy or the system. Because you can change the policy or you can change the system. So you can't put both of them.

So the policy says that the system should have this particular additional sign, additional signatures required, required. So that particular policy has to be implemented inside the system So if you remove the policy then only the system can be correct You can just correct the system and say the policy is still like this Correct? So you have to blame the correct person and who you can actually change or do. Okay? We'll do an example to get it done. Now this set of root causes look sufficient for us for this course. Okay? Usually they fall into this. So whenever you see that CSO is using lots of paper, so you call it as non-automation process. We can just call it as a paper-based process. Okay, it's a paper-based process. Similarly, any time you notice that a certain part of the process, there is insufficient information also, or insufficient data for the business user to perform the task, you can choose lack of information. So when the cause is certain will fall into this category, just give us small terms, don't explain the root cause. Root cause should be as short as three to four terms. If these root causes will help us in the later stage. The cause will be a huge description, the root cause will be just simply one of the terms. I repeat, the issue will explain the problem and which business process, which business performance is affected. Cause will explain explain why it happened Root cost simply puts the cause into one of these categories And issue categories must be policy system policy people system process Let's see some examples. Okay. So here, this is a real estate sales process. Okay. Now let's look at the issue. The errors in the forms where the bills of the sales information is captured. So when you are capturing the sales information, there are errors. There are errors. You can also say that the errors hide more errors. More errors in the problem and so on. So which you are telling that the business performance affected is the number of errors.

And the actual performance metric is you count them. You can also say that can actually affect your completion of the sales. If there are errors, the number of sales completed will be reduced per day. Because you still keep on fixing those errors. So per day instead of making 10 sales, you'll be making only 7 to 8 sales. So you can count this in terms of number of sales completed. Now cost. See why there are why you have to capture the wills, will of sales information and in the forms, why there are errors? Because the buyers and sellers fill the paper in the forms paper form I mean fill the information in the paper form So they are filling this information in the paper form and there is chances of getting more errors. You know, right? When you are filling up in a system, as an IT person, you know that when you fill up some wrong information, immediately there will be a validation checks, correct? in JavaScript. Did you learn this validation checks? So if suppose you are writing email and if iterate is missing, you already know there's an error, it will stop. So with paper form, your number of errors will increase. So this is simply paper form using, therefore your entire process is paper based process or at least that particular situation over there is paper based process. So it falls as a process problem. Can you blame the system here? Is there any system? No, no IT system. I'm not using IT system. So don't blame the system. So don't call it as a system problem. If you say it is a system problem, then wrong. So blame the current category. Let's look at the next one. Okay? So here we are looking at The second one, errors in the forms. Why there are errors in the forms? Because the sales agent does not validate the form with correctness and completeness  In this time, let me use it and then we can compare. Why there are errors in the business plan? In last time, the buyer and seller was actually filling in the paper. So we blame them. Oh, oh, on this one.

On this one. So this one is the buyer and seller filling in the paper. Therefore, it is a process problem. This time I'm saying sales guy is not doing a proper job. Why he's not doing a proper job? Because he doesn't have a good training. So the category is inadequate training. So this time I call it as a peeping problem. Do you see the difference? Same problem, same issue, but different. Issue category is different. It is the policy. Same problem, this time. Why the buyer and seller has to fill the paper in a, fill the information in the paper form? This is because of the policy. The government policy requires the sign of the sales on paper. So it's a policy. So there are three things that happens. There are three things that are happening. So whichever category is much easier to manage, that is the category that you will be choosing. Usually the policy, like the government policies, are much difficult to change Therefore just for your project try to choose the paper process or choose the ineric paper In the real scenario if it is a government policy you have to completely ignore this issue It's a red flag that stays in your project. Just that you need to add more people who can be trained to do something and solve the problem to some extent. So that's why you can say that, okay, we cannot change the paper, but we can give more training to the salesman. So that he can check for errors. To some extent you can solve the problem using a different approach. Last one. Why there are errors in the forms? Now watch carefully. This time I say the system is not validating the form. So which means this time I am using a system to collect the data. But a feature inside the system is incorrect. There is a bug in the system or incorrect feature. So lack of system functionality. Now you can safely create. There is a system, the system has a bug, therefore it is a lack of system function. Hence I bring the system. So if the root cause is not this, you cannot claim the system.

Don't call it as a system problem. Because the root cause is the system problem, I can claim it. Okay So by doing this task you will notice there will be a machine attached to it If the machine is attached to it then you blame the system If the machine is not attached to it, don't blame the system. Here, cannot blame the system. Here, cannot blame the system. So that is the same. What is in the system integration? Okay. So if you want to say that this is a system integration problem, then you should be able to explain the cause that this system might be using, this particular task is actually coming from two systems. A system working with another system. Like eLearn, after I upload the grades, after I submit the grades, the eLearn has to push the correct grades to your ISIS system, the student system, right? OASIS, okay. So, two systems are working together. If system 1 is not pushing the data to that system or it is sending a wrong information to the system, then you will say system 1 and system 2 are not correctly included. Okay. So, going back. So, this one you understood example, lack of information you understood, lack of automation you understood? Inadequate activated flow. Inadequate activated flow is any problem with the flow of activities Any problem with the flow of activities Some activities might have to be come early might have to be brought to the later stages So any such incorrections in the activity flow blame the activity flow, readjust the activities. So here I think I told you this example. I work with the IBM workflow process, right? The process of the BPM project. And in that In this particular project we have more than 80 activities. In our first analysis, and this activity actually was taking more than 60 days or so. You can't need one chain, one customer will take 60 days. Imagine how miserable this process was. Okay? So immediately the first thing that we did is we didn't have enough time to wait until the system implementation, etc.

should be done. So what we did is we noticed there are some activities which are redundant, which are attached in a wrong workflow process and parallel activities which were not considered in a proper way, etc. So we just corrected these 80 activities workflow process. So the activities adding some parallel gateways, adjusting the activities before and later, and some redundant activities have been corrected. Just doing this one, the project took less than, adjusting these activities was like less than one week  We got approvals from the business user, they changed the process. This 60 days has reduced by 57 days, has reduced to 57 days. So they say for 3 days. It's very very powerful. Just changing the activities flow, you will correct your process. Many people ignore this one. Ok, business processing, modeling and analysis is not just providing solutions which are IP solutions. Ok, you as IS graduate should be smart enough to suggest its kind of simple solutions which are inexpensive, efficient and very quick to quick solutions. Then you can go for how to improve the remaining two pieces. Ok, that you can do. Task redundancy, okay? Redundant tasks. Late exception checks. Sometimes in the workflow you notice that exceptions are checked in the later stage So all the activities which are performed earlier will be placed And people won even realise that they have been doing it They don even realise So when you put it on the paper and you show that why this exception is happening later. And this is created. Now you put it here. Things change. Okay? System functionality, system integration and explain both. System functionality is involving only one system. system integration involves more than one systems, okay, more than one idea of the issues. Staffing, if you do not have enough people, the inadequate training, you can go into the people problem.

Sometimes people, sometimes, I mean, students argue that inadequate staffing is the process problem, because I do not have sufficient resources, okay. So rather than putting into these two different categories, in this course we decided to use it as a people problem. Okay? If you argue as a process problem, still it is not important. That's it. Okay? So we go for a break, come back, and then we will do this particular activity. Yeah.
        `.trim()

        const words = longTranscript.trim().split(/\s+/)
        const preview = words.slice(0, 20).join(' ') + '...'


        console.log('Generating AI summary for test transcript...')
        console.log('Transcript length:', longTranscript.length, 'characters')
        console.log('Word count:', words.length, 'words')
        let summary = ''

        try {

            const maxWords = 6000
            const truncatedTranscript = words.length > maxWords
                ? words.slice(0, maxWords).join(' ') + '\n\n[Transcript truncated due to length...]'
                : longTranscript

            console.log('Using transcript with', truncatedTranscript.split(/\s+/).length, 'words')

            const summaryPrompt = `You are an expert academic note-taker. Summarize this lecture transcript into clear, structured notes for revision.

Use Markdown formatting with:
- ## Headings for each major topic
- Bullet points for sub-concepts
- **Bold** for key definitions
- Highlight important examples and lecturer explanations

Keep it concise but complete — like class notes you'd review before an exam.
If the lecture included frameworks, formulas, or case examples, summarize them clearly with short explanations.

Transcript:
${truncatedTranscript}

Provide the summary in Markdown format:`

            const summaryResponse = await fetch('https://api.groq.com/openai/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${config.groqApiKey}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    model: 'llama-3.3-70b-versatile',
                    temperature: 0.3,
                    max_tokens: 2000,
                    messages: [{ role: 'user', content: summaryPrompt }]
                })
            })

            console.log('Groq API response status:', summaryResponse.status)

            if (summaryResponse.ok) {
                const summaryResult = await summaryResponse.json()
                summary = summaryResult.choices[0].message.content
                console.log('AI summary generated successfully, length:', summary.length)
            } else {
                const errorText = await summaryResponse.text()
                console.error('Summary API error:', summaryResponse.status, errorText)
                summary = 'Summary generation failed. Please review the transcript manually.'
            }
        } catch (summaryError) {
            console.error('Summary generation error:', summaryError.message)
            console.error('Full error:', summaryError)
            summary = 'Summary generation failed. Please review the transcript manually.'
        }

        const recordingId = crypto.randomUUID()


        const { error } = await supabase
            .from('recordings')
            .insert({
                id: recordingId,
                user_id: userId,
                week: week,
                audio_path: `test/${recordingId}.webm`,
                audio_size: 0,
                duration_seconds: 0,
                status: 'completed',
                transcript: longTranscript.trim(),
                summary: summary,
                preview: preview,
                word_count: words.length,
                processed_at: new Date().toISOString()
            })
            .select()
            .single()

        if (error) {
            throw new Error(`Database insert error: ${error.message}`)
        }

        return {
            success: true,
            message: 'Dummy long transcript created for testing',
            recordingId: recordingId,
            wordCount: words.length
        }

    } catch (error) {
        console.error('Test transcript error:', error)
        throw createError({
            statusCode: 500,
            message: error.message || 'Failed to create test transcript'
        })
    }
})
