<script setup>
import { ref, onMounted } from 'vue'

const participations = ref([])
const loading = ref(true)
const coinsToAward = ref({})

// Simulate API delay, to be replaced with database
onMounted(() => {
    setTimeout(() => {
        participations.value = [
            {
                id: '1',
                student_id: 'stu_001',
                description: 'Answered a question during class.',
                date: '2025-10-01',
                profiles: { full_name: 'Alice Johnson' },
            },
            {
                id: '2',
                student_id: 'stu_002',
                description: 'Helped a peer during lab.',
                date: '2025-10-02',
                profiles: { full_name: 'Bob Smith' },
            },
        ]
        loading.value = false
    }, 1000)
})

const handleReview = (id, approved) => {
    console.log(`${approved ? 'Approved' : 'Rejected'} participation with ID: ${id}`)
    participations.value = participations.value.filter(p => p.id !== id)
}

const formatDate = (dateStr) => {
    return new Date(dateStr).toLocaleDateString(undefined, {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
    })
}



// If database already exists, can use below (generated by GPT)
/*
import { useToast } from 'vue-toastification' //for the pop up message
import { supabase } from '@/integrations/supabase/client'

const participations = ref([])
const loading = ref(true)
const coinsToAward = ref({})

const toast = useToast()

const props = defineProps({
    onUpdate: {
        type: Function,
        required: true,
    },
})

onMounted(() => {
    loadParticipations()
})

const loadParticipations = async () => {
    try {
        loading.value = true
        const { data, error } = await supabase
            .from('participations')
            .select('*')
            .eq('status', 'pending')
            .order('date', { ascending: false })

        if (error) throw error

        const enriched = await Promise.all(
            data.map(async (p) => {
                const { data: profile } = await supabase
                    .from('profiles')
                    .select('full_name')
                    .eq('user_id', p.student_id)
                    .single()

                return {
                    ...p,
                    profiles: {
                        full_name: profile?.full_name || 'Unknown',
                    },
                }
            })
        )

        participations.value = enriched
    } catch (e) {
        toast.error('Failed to load participations')
    } finally {
        loading.value = false
    }
}

const handleReview = async (id, approved) => {
    try {
        const {
            data: { user },
        } = await supabase.auth.getUser()
        if (!user) return

        const coins = approved ? coinsToAward.value[id] || 1 : 0

        const { error } = await supabase
            .from('participations')
            .update({
                status: approved ? 'approved' : 'rejected',
                coins_awarded: coins,
                reviewed_by: user.id,
                reviewed_at: new Date().toISOString(),
            })
            .eq('id', id)

        if (error) throw error

        if (approved) {
            const p = participations.value.find((x) => x.id === id)
            const { data: profile } = await supabase
                .from('profiles')
                .select('coin_balance')
                .eq('user_id', p.student_id)
                .single()

            if (profile) {
                await supabase
                    .from('profiles')
                    .update({ coin_balance: profile.coin_balance + coins })
                    .eq('user_id', p.student_id)
            }
        }

        toast.success(approved ? 'Participation approved' : 'Participation rejected')
        loadParticipations()
        props.onUpdate()
    } catch (e) {
        toast.error('Review failed')
    }
}

const formatDate = (dateStr) => {
    return new Date(dateStr).toLocaleDateString(undefined, {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
    })
}
*/
</script>


<template>
    <div>
        <div v-if="loading" class="card shadow-sm p-4 text-center">
            Loading...
        </div>

        <div v-else-if="participations.length === 0" class="card shadow-sm p-4 text-center text-muted">
            No pending participations to review
        </div>

        <div v-else class="d-flex flex-column gap-4">
            <!-- This is for-loop through participationsArray btw -->
            <div v-for="p in participations" :key="p.id" class="card shadow-sm">
                <div class="card-header d-flex justify-content-between align-items-start">
                    <div>
                        <h5 class="mb-1">{{ p.profiles.full_name }}</h5>
                        <small class="text-muted">
                            {{ formatDate(p.date) }}
                        </small>
                    </div>
                    <span class="badge bg-secondary">Pending</span>
                </div>

                <div class="card-body">
                    <div class="mb-3">
                        <label class="form-label">Description</label>
                        <p class="form-control-plaintext mb-0">{{ p.description }}</p>
                    </div>

                    <div class="d-flex align-items-end gap-4 flex-wrap">
                        <!-- Awarding Coins (But it is leading to nowhere for now, also cannot get AwardCoin value cause no eg <Form>) -->
                        <div class="flex-grow-1">
                            <label :for="`coins-${p.id}`" class="form-label">Coins to Award</label>
                            <div class="input-group">
                                <span class="input-group-text">
                                    <i class="bi bi-coin text-warning"></i>
                                </span>
                                <input :id="`coins-${p.id}`" type="number" class="form-control"
                                    v-model.number="coinsToAward[p.id]" min="1" max="100" placeholder="0" />
                            </div>
                        </div>

                        <div class="d-flex gap-2">
                            <button class="btn btn-outline-success d-flex align-items-center"
                                @click="handleReview(p.id, true)">
                                <i class="bi bi-check-circle me-2"></i> Approve
                            </button>
                            <button class="btn btn-outline-danger d-flex align-items-center"
                                @click="handleReview(p.id, false)">
                                <i class="bi bi-x-circle me-2"></i> Reject
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>